### ISSUE TITLE
What does saturation function return ?

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-constraints#69]
https://github.com/humanoid-path-planner/hpp-constraints/blob/1cbe9dde3fef8ff05a6f980db056c7adb98582c6/include/hpp/constraints/solver/hierarchical-iterative.hh#L186

and what should this function return ?
https://github.com/humanoid-path-planner/hpp-constraints/blob/1cbe9dde3fef8ff05a6f980db056c7adb98582c6/src/solver/hierarchical-iterative.cc#L102

**Comment by jmirabel** [comment]
The boolean triggers the part of the code that deals with boundary constraints. The saturation function should return *true* if at least one DoF is saturated, i.e.:
```cpp
bool sat = saturate (qin, qout, saturation);
assert ( sat == (saturation.array() == 0).any() );
```
The assert above could be added to `computeSaturation`. `noSaturation` should return *false*.

Note that:
- returning *true* instead of *false* should not result in an error. It should only do void operations.
- returning *false* instead of *true* can result in violated bounds.

**Comment by florent-lamiraux** [comment]
Thank you

**Comment by jmirabel** [comment]
@florent-lamiraux There was a mistake in the assert above. I edited it.
